In [1]:
import torch
import numpy as np
import pandas as pd
from vla.action_tokenizer import RLbenchActionTokenizer
from transformers import AutoModelForVision2Seq, AutoProcessor, BitsAndBytesConfig


2024-07-12 18:46:54.049995: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-12 18:46:54.050047: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-12 18:46:54.052686: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-07-12 18:46:54.060440: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-12 18:46:55.114635: W tensorflow/compiler/tf2

In [2]:
data = torch.load('./datasets/data.pt')

In [3]:
pd.DataFrame(np.array(data['actions'])).describe()

0           1           2           3           4           5  \
count  348.000000  348.000000  348.000000  348.000000  348.000000  348.000000   
mean     0.246841    0.025256    0.978841    0.252172   -0.008189    0.373322   
std      0.119445    0.176273    0.089179    3.134317    0.015889    1.802541   
min      0.041448   -0.314564    0.870849   -3.141562   -0.042459   -3.137720   
25%      0.134491   -0.131071    0.933687   -3.140366   -0.016349   -0.852105   
50%      0.239273   -0.015119    0.934153    3.136531   -0.000378    0.434047   
75%      0.360174    0.185639    1.128460    3.140641    0.000933    1.746803   
max      0.460142    0.351269    1.130237    3.141550    0.012461    3.117370   

                6  
count  348.000000  
mean     0.675287  
std      0.468942  
min      0.000000  
25%      0.000000  
50%      1.000000  
75%      1.000000  
max      1.000000

In [4]:
data['actions'][0][3:-1]

array([-3.14016372e+00,  5.56755709e-05,  2.27393251e+00])

In [5]:
processor = AutoProcessor.from_pretrained("/media/lawrence/Work/checkpoints/openvla-7b", trust_remote_code=True)


In [6]:
action_tokenizer = RLbenchActionTokenizer(processor.tokenizer)

In [7]:
test_action = np.array([0.011, 0.011, 1.001, 0.000, 0.000, 0.000, 1])

In [15]:
processor.tokenizer.vocab_size - 

31648

In [16]:
action_tokenizer.n_bins

352

In [12]:
c = action_tokenizer(test_action)

In [13]:
action_tokenizer.decode_token_ids_to_actions(np.array([31696, 31746, 31847, 31947, 31947, 31947, 31998]))

array([0.015     , 0.01499999, 1.00499999, 0.03141592, 0.03141592,
       0.03141592, 0.        ])

In [11]:
data['actions'][0]

array([ 2.41797626e-01,  2.65482694e-01,  9.34287667e-01, -3.14016372e+00,
        5.56755709e-05,  2.27393251e+00,  1.00000000e+00])